- src/main/scala/dd2d/InboxMonitor.scala
Not calling `watcher.stop()` seems to resolve the problem. However, I have only tested this with an empty inbox. Please, test what happens if queue is still busy processing.
> DD-111. dd-dans-deposit-to-dataverse throws exception when service is stopped

- src/main/scala/dd2d/Configuration.scala
- src/main/scala/dd2d/DansBagValidationResult.scala
- src/main/scala/dd2d/DepositIngestTask.scala
- src/main/scala/dd2d/ValidateBag.scala
- src/main/scala/dd2d/package.scala
- src/test/scala/dd2d/ReadmeSpec.scala
Fixes EASY-[DD-107](https://drivenbydata.atlassian.net/browse/DD-107)
* **Note: not merge ready yet. It worked but issues with `easy-validate-dans-bag` service must be resolved first.**
see: https://drivenbydata.atlassian.net/browse/EASY-2771
> DD-107 - Call easy-validate-dans-bag before mapping/ingesting deposit to Dataverse dataset

- src/main/assembly/dist/install/dd-dans-deposit-to-dataverse.service
- src/main/scala/dd2d/DdmToDataverseMapper.scala
- src/main/scala/dd2d/DepositIngestTask.scala
- src/main/scala/dd2d/dataverse/Dataverse.scala
- src/main/scala/dd2d/dataverse/HttpSupport.scala
- src/main/scala/dd2d/dataverse/json/package.scala
- src/test/resources/debug-config/application.properties
- src/test/scala/dd2d/EasyToDataverseMapperSpec.scala
Fixes [DD-106](https://drivenbydata.atlassian.net/browse/DD-106)
* To test: replace the content of the dataset.xml file in `data/inbox/valid-easy-submitted/example-bag-medium/metadata/dataset.xml` with content of the attached file. This because the controlled vocabularies used in EASY ddm do no match those in Dataverse (yet).
[dataset.txt](https://github.com/DANS-KNAW/dd-dans-deposit-to-dataverse/files/5200591/dataset.txt)
* **Note: decisions  about file metadata mapping still have to be made.** 
> When adding a file to a dataset, you can optionally specify the following:
> 
>     A description of the file.
>     The “File Path” of the file, indicating which folder the file should be uploaded to within the dataset.
>     Whether or not the file is restricted.
_source: …
> DD-106 - Include files + file metadata to dd-dans-deposit-to-dataverse

- src/main/scala/nl.knaw.dans.easy.dd2d/dataverse/HttpSupport.scala
Fixes EASY-202
* The problem is fixed by calling http MultiPart with `FileInputStream`
repo                       | PR                | note
-------------------------- | ----------------- | ----
easy-                      | [PR#](PRlink)     | ..
> DD-202: OutOfMemoryError when uploading file data with dd-dans-deposit-to-dataverse

- src/main/scala/nl.knaw.dans.easy.dd2d/DepositSorter.scala
Fixes [DD-269](https://drivenbydata.atlassian.net/browse/DD-269)
Note: the problem wasn't about related pairs of deposits but about a `NoSuchElementException` being thrown for a non-existent key.
Added check on existence of key in Map
1. Deploy module on dd-dtap
2. import dataset attached in Jira issue (https://drivenbydata.atlassian.net/browse/DD-269)
(Add links)
* 
> Fixed deposit sorting bug

- src/main/scala/nl.knaw.dans.easy.dd2d/DepositSorter.scala
Fixes DD-283
* add missing `!` to fix the filter for `datasetsWithoutFirstVersions`.
* Follow steps in the issue on Jira
(Add links)
* 
> DD-283: fix "No first version was found for dataset"

- src/main/scala/nl.knaw.dans.easy.dd2d/mapping/Audience.scala
- src/main/scala/nl.knaw.dans.easy.dd2d/mapping/Format.scala
- src/main/scala/nl.knaw.dans.easy.dd2d/mapping/Language.scala
- src/main/scala/nl.knaw.dans.easy.dd2d/mapping/SubjectAbr.scala
- src/main/scala/nl.knaw.dans.easy.dd2d/mapping/TemporalAbr.scala
- src/main/scala/nl.knaw.dans.easy.dd2d/mapping/Type.scala
- src/main/scala/nl.knaw.dans.easy.dd2d/mapping/package.scala
Fixes DD-280
See: https://drivenbydata.atlassian.net/browse/DD-280
1. Check out pr
2. Run `mvn clean install`
3. Deploy in dd-dtap: `./deploy-module.sh dd-dans-deposit-to-dataverse ` 
4. Add `    
<dcterms:format>application/pdf</dcterms:format>
<dcterms:type>Dataset</dcterms:type>
<dc:format>text/html</dc:format>
<dc:language xsi:type='dcterms:ISO639-2'>fre</dc:language>
<dcterms:temporal xsi:type="abr:ABRperiode">PALEOLA</dcterms:temporal>`
to a test bags `dataset.xml`.
5. Disable bag validator in dtap (the xml won't validate but this is for testing only): `systemctl stop easy-validate-dans-bag`
6. Run: `vagrant ssh`
7. Copy test bag to inbox: `sudo cp -r /vagrant/{testbagdir} /var/opt/dans.knaw.nl/tmp/deposits-inbox/`
8. Run: `dd-dans-deposit-to-dataverse import …
> Refactoring Controlled Vocabulary classes

- src/main/scala/nl.knaw.dans.easy.dd2d/mapping/Audience.scala
- src/test/scala/nl.knaw.dans.easy.dd2d/mapping/AudienceSpec.scala
Fixes DD-323
* Changed `toCitationBlockSubject` to throw a `RuntimeException` when an invalid NARCIS classification code is given.
* otherwise `toCitationBlockSubject` returns the correct Dataverse subject.
* Changed `getTermAndUrl` to only returns the English term.
* Changed `AudienceSpec` to test new behavior.
(Add links)
* 
> DD-323: fix NARCIS to Dataverse subject mapping and restrict audience term to english

- src/main/assembly/dist/cfg/application.properties
- src/main/scala/nl.knaw.dans.easy.dd2d/Command.scala
- src/main/scala/nl.knaw.dans.easy.dd2d/CommandLineOptions.scala
- src/main/scala/nl.knaw.dans.easy.dd2d/Configuration.scala
- src/main/scala/nl.knaw.dans.easy.dd2d/DansDeposit2ToDataverseApp.scala
- src/main/scala/nl.knaw.dans.easy.dd2d/DepositIngestTask.scala
- src/main/scala/nl.knaw.dans.easy.dd2d/Inbox.scala
- src/main/scala/nl.knaw.dans.easy.dd2d/SingleDepositProcessor.scala
- src/main/scala/nl.knaw.dans.easy.dd2d/package.scala
- src/test/resources/debug-config/application.properties
- src/test/scala/nl.knaw.dans.easy.dd2d/DepositIngestTaskSortSpec.scala
- src/test/scala/nl.knaw.dans.easy.dd2d/IndexSpec.scala
Fixes [DD-357](https://drivenbydata.atlassian.net/browse/DD-357)
Deposits are moved to designated outdir after import.
**Using default outdir**
vagrant ssh
`cp -r <depositdir> /var/opt/dans.knaw.nl/tmp/deposits-inbox`
`dd-dans-deposit-to-dataverse run-service`
Check if dirs are created in `/var/opt/dans.knaw.nl/tmp/deposits-outbox` and the `deposits-processed` subdirectory contains the deposit.
**Using --outdir command line option**
vagrant ssh
`dd-dans-deposit-to-dataverse import --<outdir> -s <depositdir>`
Check if dirs are created in specified outdir and the `deposits-processed` subdirectory contains the imported deposit.
Do the same with an invalid and a failed deposit to see that they are placed in respectively the `deposits-rejected` and `deposits-failed` directories.
(Add links)
* …
> DD-357 - Separate folders for processed, failed and rejected deposits

- src/main/scala/nl.knaw.dans.easy.dd2d/CommandLineOptions.scala
- src/main/scala/nl.knaw.dans.easy.dd2d/DansDeposit2ToDataverseApp.scala
- src/main/scala/nl.knaw.dans.easy.dd2d/DepositIngestTask.scala
- src/main/scala/nl.knaw.dans.easy.dd2d/Inbox.scala
- src/main/scala/nl.knaw.dans.easy.dd2d/SingleDepositProcessor.scala
- src/main/scala/nl.knaw.dans.easy.dd2d/package.scala
Fixes DD-357
* Changed the `--outdir` option to a second trailing argument, as that was more intuitive when using the command line.
* Removed `initOutboxDirs` from the service start-up, as the outdir may be non-empty when the service restarts, and that is not a problem.
* Made sure the resulting Try of `initOutboxDirs` is used.
* Changed `java.nio.Path` to `better.files.File` in a couple of places.
* Fixed a problem with the subdirectory names, which were interpreted as absolute paths.
(Add links)
* 
> DD-357. Some improvements

- src/main/scala/nl.knaw.dans.easy.dd2d/DansDeposit2ToDataverseApp.scala
- src/main/scala/nl.knaw.dans.easy.dd2d/Deposit.scala
- src/main/scala/nl.knaw.dans.easy.dd2d/DepositIngestTask.scala
- src/main/scala/nl.knaw.dans.easy.dd2d/DepositToDataverseMapper.scala
- src/main/scala/nl.knaw.dans.easy.dd2d/Inbox.scala
- src/main/scala/nl.knaw.dans.easy.dd2d/SingleDepositProcessor.scala
- src/main/scala/nl.knaw.dans.easy.dd2d/mapping/BlockCollection.scala
- src/main/scala/nl.knaw.dans.easy.dd2d/mapping/BlockRights.scala
- src/main/scala/nl.knaw.dans.easy.dd2d/mapping/Collection.scala
- src/main/scala/nl.knaw.dans.easy.dd2d/mapping/DateTypeElement.scala
- src/main/scala/nl.knaw.dans.easy.dd2d/mapping/Description.scala
- src/main/scala/nl.knaw.dans.easy.dd2d/mapping/PersonalStatement.scala
- src/main/scala/nl.knaw.dans.easy.dd2d/mapping/SpatialCoverage.scala
- src/test/resources/examples/valid-easy-submitted/example-bag-medium/metadata/depositor-info/agreements.xml
- src/test/resources/examples/valid-easy-submitted/example-bag-medium/tagmanifest-sha1.txt
- src/test/scala/nl.knaw.dans.easy.dd2d/DepositIngestTaskSortSpec.scala
- src/test/scala/nl.knaw.dans.easy.dd2d/DepositToDataverseMapperSpec.scala
- src/test/scala/nl.knaw.dans.easy.dd2d/mapping/PersonalStatementSpec.scala
- src/test/scala/nl.knaw.dans.easy.dd2d/mapping/SpatialPointSpec.scala
Fixes DD-369
* Blocks are now only filled in if they are present and active in the target dataverse
* Implemented more mappings: dansCollection, dansPersonalDataPresent
* Improved checks on existing output for `import` command: when doing a single deposit, outdir does not need to be empty, but the same deposit must not be there.
* Fixed location scheme bug on Points.
(Add links)
* 
> DD-369 Let dd-dans-deposit-to-dataverse only try to fill in active metadata blocks + more md mappings

- src/main/scala/nl.knaw.dans.easy.dd2d/mapping/Language.scala
- src/test/scala/nl.knaw.dans.easy.dd2d/mapping/LanguageSpec.scala
Fixes DD-413
* See issue
* Tested with https://easy.dans.knaw.nl/ui/datasets/id/easy-dataset:66365 for which the bug was reported.
> DD-413 Language mapping should take language code instead of human-readable term as input value

- src/main/scala/nl.knaw.dans.easy.dd2d/DatasetCreator.scala
- src/main/scala/nl.knaw.dans.easy.dd2d/DatasetEditor.scala
- src/main/scala/nl.knaw.dans.easy.dd2d/DatasetUpdater.scala
- src/main/scala/nl.knaw.dans.easy.dd2d/DepositIngestTask.scala
- src/main/scala/nl.knaw.dans.easy.dd2d/mapping/Amd.scala
- src/main/scala/nl.knaw.dans.easy.dd2d/package.scala
Fixes DD-449
added support for import of publication date
1. Use latest archaeology base box
2. check out https://github.com/DANS-KNAW/dans-dataverse-scala-lib/pull/10 and run mvn clean install
3. check out this pr and run mvn clean install (this should add dans-dataverse-scala-lib to the dependencies)
4. check out  https://github.com/IQSS/dataverse/pull/7504 and run mvn clean install
5. redeploy .war file in dd-dtap
6. deploy module dd-dans-deposit-to-dataverse in dd-dtap
7. import a dataset with an amd file
8. Check the publication date
(Add links)
* https://github.com/DANS-KNAW/dans-dataverse-scala-lib/pull/10
> DD-449 - Use "release migrated" function from dans-deposit-to-dataverse

- src/main/scala/nl.knaw.dans.easy.dd2d/Command.scala
- src/main/scala/nl.knaw.dans.easy.dd2d/DatasetCreator.scala
- src/main/scala/nl.knaw.dans.easy.dd2d/Deposit.scala
- src/main/scala/nl.knaw.dans.easy.dd2d/DepositIngestTask.scala
- src/main/scala/nl.knaw.dans.easy.dd2d/package.scala
Fixes DD-405
* Waits for the dataset to become unlocked after publication and get status "RELEASED" , then reads the URN:NBN from the dataset (it should be set by the prepublication workflow) and writes it to the `deposit.properties` along with the DOI.
* Writes the state.label and state.description to `deposit.properties` before moving the deposit to the appropriate outbox subdirectory.
* Does not support update-deposits yet. I will do this in a separate issue, as some refactoring of the code, to untangle the migration and SWORD oriented code should be done first.
Use the `easy-sword2-dans-examples` project.
(Add links)
* 
> DD-405 Write properties used by easy-sword2 to create a statement for the client

- src/main/scala/nl.knaw.dans.easy.dd2d/DepositToDvDatasetMetadataMapper.scala
Fixes DD-453
Added a check that `dansRightsHolder` is filled in the mapper (as is done for all required fields). This is a double-check in most cases because the DDM schema already requires the field to be filled.
To test this you would need to disable the DDM schema validation and input a deposit without a rights holder.
(Add links)
* 
> DD-453 Added required field check in mapper for dansRightsHolder

- docs/index.md
- src/main/assembly/dist/cfg/logback-service.xml
- src/main/assembly/dist/cfg/logback.xml
- src/main/scala/nl.knaw.dans.easy.dd2d/Command.scala
- src/main/scala/nl.knaw.dans.easy.dd2d/CommandLineOptions.scala
- src/main/scala/nl.knaw.dans.easy.dd2d/DansDeposit2ToDataverseApp.scala
- src/main/scala/nl.knaw.dans.easy.dd2d/DepositIngestTask.scala
- src/main/scala/nl.knaw.dans.easy.dd2d/DepositIngestTaskFactory.scala
- src/main/scala/nl.knaw.dans.easy.dd2d/DepositMigrationTask.scala
NO JIRA.
* Added option `--skip-validation` to the `import` subcommand. This will cause the call to `easy-validate-dans-bag` to be skipped. At the time of writing the immediate need for this is due to a test export that turns out not to validate, but can still be imported. In the longer run this may still be a useful feature. You could do an export, prevalidate it and then skip validation during import.
* Corrected some docs.
* Removed the `--draft` option, which allowed you to import a dataset and keep it on draft. This does not seem useful for the migration in retrospect.
* Made the `inboxWatcher` field on the App object lazy. This prevents the program from trying to create the outbox dirs for the *service* when doing an `import` (which results in a permission denied, because the user …
> Built in an option to skip validation during import

- docs/index.md
- pom.xml
- src/main/scala/nl.knaw.dans.easy.dd2d/DatasetCreator.scala
- src/main/scala/nl.knaw.dans.easy.dd2d/DatasetEditor.scala
- src/main/scala/nl.knaw.dans.easy.dd2d/DatasetUpdater.scala
- src/main/scala/nl.knaw.dans.easy.dd2d/DepositIngestTask.scala
- src/main/scala/nl.knaw.dans.easy.dd2d/mapping/AccessRights.scala
- src/test/scala/nl.knaw.dans.easy.dd2d/mapping/AccessRightsSpec.scala
Fixes DD-472
Implemented the following rule (from the docs site):
> *If one or more files in the dataset (in any of its version) have an (effective) accessibility of `NONE`, permission requests will be disabled; otherwise they will be enabled.* 
I was not sure if files always have explicit declarations of their accessibleToRights. For the behavior to work it should not be necessary. The access category of the dataset will be used to find the effective accessibleToRights if it is omitted.
This can be tested by creating deposits with various combinations of file accessiblities and categories. The unit tests in `nl.knaw.dans.easy.dd2d.mapping.AccessRightsSpec` should cover most cases. However the unit tests do not cover the rule that an update deposit can only **remove** the "allow …
> DD-472 Implement mapping of file accessibility

- src/main/scala/nl.knaw.dans.easy.dd2d/DatasetUpdater.scala
Fixes DD-518
Because of the problem described in DD-518 occasionally popping up `dd-dans-deposit-to-dataverse` searched only on the UUID-part of `dansSwordToken` when trying to find the target of an update-deposit. The resolution in https://github.com/DANS-KNAW/dd-dtap/pull/120 means that searches for the SWORD token must now specify the full token, including the `sword:` prefix.
* Try and update deposit.
* https://github.com/DANS-KNAW/dd-dtap/pull/120
> DD-518. SWORD2 update-deposit fails because SWORD-token cannot be found in index

- pom.xml
- src/main/assembly/dist/cfg/application.properties
- src/main/scala/nl.knaw.dans.easy.dd2d/Configuration.scala
- src/main/scala/nl.knaw.dans.easy.dd2d/DansDepositToDataverseApp.scala
- src/main/scala/nl.knaw.dans.easy.dd2d/DatasetCreator.scala
- src/main/scala/nl.knaw.dans.easy.dd2d/DatasetEditor.scala
- src/main/scala/nl.knaw.dans.easy.dd2d/DatasetUpdater.scala
- src/main/scala/nl.knaw.dans.easy.dd2d/DepositIngestTask.scala
- src/main/scala/nl.knaw.dans.easy.dd2d/DepositIngestTaskFactory.scala
- src/main/scala/nl.knaw.dans.easy.dd2d/DepositMigrationTask.scala
- src/test/resources/debug-config/application.properties
- src/test/scala/nl.knaw.dans.easy.dd2d/IndexSpec.scala
Fixes DD-560 and DD-547
* Make sure the correct file metadata is passed for updating replaced files' metadata.
* Make sure file metadata is also replaced for files that do not change otherwise.
* Adds a setting `deposits.file-exclusion-pattern`. The value must be a valid regular expression. Files of which the path relative to the `data/` folder of their parent bag matches the pattern are excluded from the import. An info message is logged to notify the user calling import.
See related PR.
* https://github.com/DANS-KNAW/dd-dtap/pull/129
> DD-560 easy-migration directoryLabel lost in second version

- src/main/scala/nl.knaw.dans.easy.dd2d/DatasetCreator.scala
- src/main/scala/nl.knaw.dans.easy.dd2d/DatasetEditor.scala
- src/main/scala/nl.knaw.dans.easy.dd2d/DatasetUpdater.scala
Fixes DD-700
files in `easy-migration` don't come under `embargo`
(Add links)
* 
> DD-700: Exclude easy-migration metadata files from embargo

- src/main/scala/nl.knaw.dans.easy.dd2d/DepositToDvDatasetMetadataMapper.scala
- src/main/scala/nl.knaw.dans.easy.dd2d/mapping/Publisher.scala
Fixes DD-615
Adds mapping from `publisher` field to `distributor`.
Import a deposit with `dcmiMetadata/publisher` filled in.
> DD-615. Map publisher field

- src/main/scala/nl.knaw.dans.easy.dd2d/DepositToDvDatasetMetadataMapper.scala
Fixes NO JIRA
In the fix for DD-716 a copy-paste error was committed by myself, which leads to invalid contributor metadata (namely, with subfields that belong in the author field).
Import datasets with contributor metadata.
#81 
> Fixed regression bug, introduced in 005f002b

- src/main/scala/nl.knaw.dans.easy.dd2d/DatasetCreator.scala
- src/main/scala/nl.knaw.dans.easy.dd2d/DatasetEditor.scala
- src/main/scala/nl.knaw.dans.easy.dd2d/DatasetUpdater.scala
Fixes NO JIRA
Created fix together with @lindareijnhoudt 
This should resolve the problem 'cannot edit metadata on replaced file'  that occurred in a handful of cases during the demo import this week. The problem was caused by the following situation:
* Version 1 of the dataset contained a file A
* The update deposit resulted in a renaming of A to B (i.e. the checksum of a file B was equal to that of A)
* The update deposit also contained a file A (with a different checksum than A in version 1), thus triggering a replacement of A with new content.
The move action (second bullet) is implemented as a metadata update on the file. However this file had just been replaced as a result of the replace action (third bullet). Dataverse correctly does not allow you to modify the metadata of a file …
> NO JIRA. Solve 'cannot edit metadata on replaced file'

- src/main/scala/nl.knaw.dans.easy.dd2d/DepositToDvDatasetMetadataMapper.scala
Fixes DD-730
Remove `dateSubmitted` from the list of fields to be migrated to a description element.
Migrate a dataset with "date submitted" filled in (in the form).
> DD-730. Don't migrate 'date submitted'

- src/main/scala/nl.knaw.dans.easy.dd2d/DatasetUpdater.scala
- src/main/scala/nl.knaw.dans.easy.dd2d/Deposit.scala
Fixes DD-748
* Look up target of update by `Is-Version-Of`. This should be the value of `dansBagId` for one of the previous dataset versions. Typically, the first dataset version should be used, but since they all have the same DOI it doesn't really matter.
Import a version-sequence, preferably in a dataverse that already has some datasets.
> DD-748 dd-dans-deposit-to-dataverse: look up existing DOI through Is-Version-Of instead of deposit.dataversePid

- src/main/scala/nl.knaw.dans.easy.dd2d/mapping/DcxDaiAuthor.scala
- src/test/scala/nl.knaw.dans.easy.dd2d/mapping/DcxDaiAuthorSpec.scala
Fixes DD-717
when parsing `rightsHolder` from `dcx-author`, `titles` and `organization` are included 
(Add links)
* 
> DD-717: Rights holder is not deduplicated in specific cases

- src/main/scala/nl.knaw.dans.easy.dd2d/mapping/AbrScheme.scala
- src/main/scala/nl.knaw.dans.easy.dd2d/mapping/TemporalAbr.scala
- src/test/scala/nl.knaw.dans.easy.dd2d/mapping/TemporalAbrSpec.scala
Fixes DD-398
* Extended the method that recognizes an ABR period value in a `temporal` element to include those that use as `schemeURI` the general ABR+ uri and as  `subjectScheme` the corresponding name.
> DD-398. Added support for abr temporal as specified by PAN

- src/main/scala/nl.knaw.dans.easy.dd2d/DepositToDvDatasetMetadataMapper.scala
- src/main/scala/nl.knaw.dans.easy.dd2d/mapping/DatesOfCollection.scala
- src/test/scala/nl.knaw.dans.easy.dd2d/mapping/DatesOfCollectionSpec.scala
Fixes DD-818
* Map `ddm:datesOfCollection` text value in the format `start/end` to `dateOfCollection` field.
* Assumes that the format has been checked by `easy-validate-dans-bag`.
* I have not verified if Dataverse handles year-month or year-only dates well.
> DD-818 Implemented mapping of datesOfCollection to dateOfCollection field
